name: validate

on:
  push:
  pull_request:

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pak
          needs: check
      - name: Run tests
        run: Rscript -e 'testthat::test_dir("tests/testthat")'
      - name: Reproduce analysis
        run: Rscript run.R
